extends:
  - "@35up/35up-base"
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - tsconfig.json
    - tsconfig.test.json
plugins:
  - '@typescript-eslint'
env:
  browser: true
  es6: true
overrides:
  - files:
    - '**/*.test.*'
    - '**/*.spec.*'
    rules:
      '@typescript-eslint/no-non-null-assertion': off

